name: Sync README Translation

on:
  push:
    paths:
      - "README-zh_CN.md" # 当简体中文版的README发生更改时触发

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js (required for translation tools)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Translation Tool
      run: npm install -g opencc-cli # 安装 OpenCC，用于简繁转换

    - name: Translate README and Commit Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 翻译 README-zh_CN.md 内容到 README.md
        npx opencc --config s2t.json < README-zh_CN.md > README.md
        
        # 获取最近一次的 commit message
        LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        
        # 将 commit message 翻译成繁体中文
        TRANSLATED_MESSAGE=$(echo "$LAST_COMMIT_MESSAGE" | npx opencc --config s2t.json)
        
        # 追加指定的额外信息到 commit message
        COMMIT_MESSAGE="$TRANSLATED_MESSAGE\n\n同步自对简体中文版本的修改，您可以对此修改进行评论或者提交您自己的修改来改进。\nSynced from a edit to the simplified Chinese version, please comment on this commit or just commit your own changes to improve."
        
        # 提交更改到仓库
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "$COMMIT_MESSAGE"
        git push
