name: Sync README-zh_CN.md and README.md

on:
  push:
    branches: [ main ]
    paths:
      - 'README-zh_CN.md'
      - 'README.md'

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install OpenCC
        run: sudo apt-get install opencc
      - name: Determine modified file
        id: determine_file
        run: |
          if [[ -n "$GITHUB_EVENT_PATH" ]]; then
            modified_file=$(cat $GITHUB_EVENT_PATH | jq -r '.changes[] | select(.added || .modified) | .filename')
          else
            echo "::error title=Failed to determine modified file::No modified file found."
            exit 1
          endif
          echo "::set-output name=modified_file::$modified_file"
      - name: Check for noaction keyword
        if: steps.determine_file.outputs.modified_file != ''
        run: |
          commit_message=$(git log -1 --format=%B)
          if [[ $commit_message == *"noaction"* ]]; then
            echo "::warning title=Noaction keyword detected::Skipping synchronization."
            exit 0
          fi
      - name: Translate and sync
        if: steps.determine_file.outputs.modified_file != ''
        run: |
          # Determine source and target files
          if [[ "${steps.determine_file.outputs.modified_file}" == "README-zh_CN.md" ]]; then
            source_file="README-zh_CN.md"
            target_file="README.md"
            opencc_config="-c t2s"
          else
            source_file="README.md"
            target_file="README.md"
            opencc_config="-c s2t"
          fi
          # Translate modified content
          git diff --name-only HEAD^ HEAD | xargs -I {} sh -c 'opencc {} -o {}.tmp $opencc_config'
          # Replace original content with translated content
          mv *.tmp *.md
          # Commit changes
          git add $target_file
          git commit -m "$(opencc "$commit_message" $opencc_config)"
          git push
